### ISSUE TITLE
Замена mimeTeX

### ISSUE THREAD

**Issue by Michael-Riddler** [Jenyay/outwiker#13]
Есть ли возможность заменить mimeTeX на что-то более симпатичное? Или как-то кастомизировать вид формул?

**Comment by Jenyay** [comment]
Я смотрел еще один движок, но уж больно он был большой, несколько десятков МБ, которые придется добавлять к каждой странице с формулами. Надо подумать, можно ли его не прикреплять к каждой странице.

**Comment by Michael-Riddler** [comment]
Как насчёт MathJax и вообще поддержки JavaScript?

**Comment by Jenyay** [comment]
По-моему, я его и смотрел. Или что-то другое, что работает через JS.

**Comment by unreal666** [comment]
По мне так лучше mimeTeX - не надо в страницы всякие левые js пихать.

**Comment by Michael-Riddler** [comment]
mimeTeX работает, но по мне так уж больно формулы убогие. Плюс нельзя свои команды вводить. В этом смысле мне по душе stackedit.io

**Comment by Jenyay** [comment]
Внешний вид формул mimeTex мне тоже не нравится.

**Comment by Michael-Riddler** [comment]
Ещё один минус в ненастраиваемости вида формул — так как цвет только чёрный, с тёмными темами формул просто не видно.

**Comment by Jenyay** [comment]
В новой версии плагина [TeXEquation](http://jenyay.net/Outwiker/TexEquation) вместо mimeTeX используется KaTeX , и проблема с формулами решена.
