### ISSUE TITLE
Релиз 1.9

### ISSUE THREAD

**Issue by sergeyklay** [Jenyay/outwiker#14]
Год назад я спросил, когда же будет стабильная версия (1.9).
Насколько я помню речь шла о "в конце года". Уже начало следующего. Где? :)

Пишу здесь, а не в комментарии к http://jenyay.net/blog/2015/12/30/outwiker-razvitie-v-2015-godu-i-plany-na-2016-god/ потому что на сайте, какие бы email/имя не использовал, получаю вот это:
![selection_067](https://cloud.githubusercontent.com/assets/1256298/12159165/b36a137c-b4e8-11e5-992f-f0aa0d615e6c.png)

**Comment by Jenyay** [comment]
Я же там написал, что доделаю плагин для скачивания страниц из интернета, а потом буду готовиться к релизу. Пока ориентируюсь на март, если ничего особенного не выявится.

**Comment by Jenyay** [comment]
Поскольку релиз уже состоялся, ветку закрываю.
