### ISSUE TITLE
Не создавать "__icon.png" для иконки по-умолчанию

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#140]
Это уменьшит количество файлов. Соответственно, возрастет скорость записи на флешки (маленькие файлы на флешки копируются очень медленно) и скорость закачки через интернет с телефона (пользуюсь SugarSync для синхронизации папки с заметками).

**Comment by twobolts** [comment]
поправлено?

**Comment by Jenyay** [comment]
Да. Спасибо, закрываю.
