### ISSUE TITLE
Предупреждение "iCCP: known incorrect sRGB profile"

### ISSUE THREAD

**Issue by unreal666** [Jenyay/outwiker#16]
При открытии некоторых вики вылазит окошко с данным предупреждением.

Версия Outwiker - 2.0.0.792.
Наверно связано с моими пользовательскими иконками для значков страниц в дереве вики.
В версии 1.9.x этого предупреждения не было.
ОС: Win7 x64

**Comment by Jenyay** [comment]
А можешь прислать пример такого значка?

**Comment by unreal666** [comment]
Сейчас проверил на тестовой вики. Ни на один из моих значков не матерится. Да и по повторной думке - на мои как раз не должен матюкаться. т.к. они все пропущены через "уменьшители" png, типа PNGOUTWin и FileOptimizer, т.е. все лишняя инфа из них выкинута.
Значит скорее всего какой-то из твоих встроенных, только какой непонятно - у меня в вики их много используется.

**Comment by unreal666** [comment]
хотя не. Все-таки у меня. Просто на момент использования значки еще не оптимизировались.

Вот ссылка - https://yadi.sk/d/vnsOr6cmrttoX .
В архиве, чтобы не сайт ничего с ней не сделал.

**Comment by Jenyay** [comment]
Это известная проблема в wxWidgets - http://trac.wxwidgets.org/ticket/15360. Ее уже исправили в wxWidgets 3.1, но до wxPython эта версия еще не добралась. Отключил подобные предупреждения wxPython глобально, от них все равно толку нет.
