### ISSUE TITLE
UpdateNotifier plugin does not seem to be working

### ISSUE THREAD

**Issue by airone506** [Jenyay/outwiker#195]
The UpdateNotifier plugin does not seem to be working.

OutWiker version: 2.0.0.812 beta
UpdateNotifier plugin version: 1.1.3

After clicking on `Help --> Check for Updates...` the UpdateNotifier dialog with progressbar is displayed. After it disappears, only the text `Check for new versions...` appears on OutWiker statusbar and it remains there until some other action in the program GUI has been performed. I would expect the  attached dialog to be displayed, however, it is not displayed. The dialog has been displayed in the previous versions. I do not remember the exact number of the last version it woked, but it was some pre-2.x version probably. _(screenshot sourced directly from the OutWiker website)_

![UpdateNotifier dialog](http://jenyay.net/uploads/Outwiker/UpdateNotifierEn/updatenotifier_en_linux.png)

**Comment by adeptg** [comment]
updatenotifier-1.1.3 doesn't work for me either. For me outwiker even can't start with it on Ubuntu 16.04, Unity 7, outwiker 2.0.0+814~xenial.
Nothing interesting with --debug option was displayed. Application just doesn't show up.

**Comment by Jenyay** [comment]
About mistakes with the launch in Ubuntu 16.04 do, please separate topic. 
If you run the "outwiker" command in the console, does something appear?

PS. Можно и по-русски :)

**Comment by adeptg** [comment]
@Jenyay done https://github.com/Jenyay/outwiker/issues/340

> PS. Можно и по-русски :)

I think that it'll be more convenient for international contributors to read my bad English than translate my Russian :)

**Comment by Jenyay** [comment]
I fix a bug that interfered with UpdateNotifier work. Please, try new OutWiker version - http://jenyay.net/Outwiker/UnstableEn

**Comment by airone506** [comment]
I just tested the new version. It works fine now.
