### ISSUE TITLE
Установка / обновление плагинов через интерфейс программы

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#311]

**Comment by twobolts** [comment]
Для установки плагинов из интерфейса программы нужен единый список всех доступных плагинов со ссылками на xml c информацией о плагин. 
Например это может быть xml по адресу:
http://jenyay.net/uploads/Outwiker/Plugins.xml

p.s. можно конечно парсить страницу http://jenyay.net/Outwiker/Plugins и пытаться оттуда получить нужные данные по каждому плагину, но мне кажется, что это перебор.

**Comment by Jenyay** [comment]
Можно для начала в самом UpdateNotifier хранить список имеющихся плагинов. Я надеюсь когда-нибудь дойдут руки, чтобы сделать отдельный сайт для OutWiker, и тогда можно будет сделать web API для всего этого дела.

**Comment by twobolts** [comment]
Ready!
