### ISSUE TITLE
Markdown. Раскраска исходников

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#331]

**Comment by Jenyay** [comment]
Сделано в версии 1,3 плагина Markdown.

**Comment by Slavinsky** [comment]
Спасибо, а можно увидеть пример с расказкой, у меня форматирует но не раскашивает

**Comment by Jenyay** [comment]
![code](https://user-images.githubusercontent.com/166281/28718206-9b6e989e-73ad-11e7-88bf-4174225f4bd5.jpg)
![html](https://user-images.githubusercontent.com/166281/28718205-9b6bb890-73ad-11e7-8882-16e647e16f91.jpg)
