### ISSUE TITLE
UpdateNotifier plugin prevents outwiker from start

### ISSUE THREAD

**Issue by adeptg** [Jenyay/outwiker#340]
Hello
First of all: thanks for outwiker!

On Ubuntu 16.04 with Unity 7 outwiker can't start with UpdateNotifier 1.1.3

> $ ls ~/.config/outwiker/plugins
> updatenotifier

> $ outwiker --debug
> Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x2e057a0)" of type `gboolean'
12:05:39 AM: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined

And nothing happened - I can't see application running

> $ rm -r  ~/.config/outwiker/plugins/updatenotifier/
> $ outwiker --debug
> Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x28cd7a0)" of type `gboolean'
12:07:12 AM: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined

So output is the same but application starts and running

**Comment by Jenyay** [comment]
Start OutWiker without UpdateNotifier plugin?

**Comment by adeptg** [comment]
Yes now I'm running outwiker (sorry I forget to mention that my outwiker is 2.0.0+814~xenial version) without  UpdateNotifier

**Comment by Jenyay** [comment]
I fix a bug that interfered with UpdateNotifier work. Please, try new OutWiker version - http://jenyay.net/Outwiker/UnstableEn
