### ISSUE TITLE
TeXEquation 2.0.2 won't work with IE8 in windows

### ISSUE THREAD

**Issue by Dmtr0** [Jenyay/outwiker#353]
WxWebView в windows использует IE, в котором KaTeX не особо правильно отображается, а в моем случае вообще не отображается (IE8). Может стоить сделать настройку для включения использования старого движка. Я пока не нашел как можно включить использование WebKit в WxPython для Windows. 
Может стоить посмотреть в сторону CEF Python ( https://github.com/cztomczak/cefpython ) Есть примеры и для wxPython. 
__content.html в других броузерах открывается корректно.
B IE ошибка:
Сообщение: Недопустимый диапазон в наборе знаков
Строка: 1
Символ: 6467
Код: 0
URI-код: file:///{путь правильный}/__attach/__thumb/katex/katex.min.js

**Comment by Jenyay** [comment]
А можете прислать пример страницы с ошибкой?

**Comment by Dmtr0** [comment]
Может неправильно понял, но вот что получается из такой вики-записи:
!! Пример викистраницы с формулой

{$y=x\times 5$}

https://pastebin.com/KntAexVp

**Comment by Jenyay** [comment]
Попробуйте новую версию плагина TeXEquation. Теперь используется новая версия KaTeX, в которой было сделано много исправлений.
