### ISSUE TITLE
Не удаётся установить

### ISSUE THREAD

**Issue by MakarevichDmitry** [Jenyay/outwiker#354]
Лог:

(C:\ProgramData\Miniconda3) C:\Users\Makarevich>activate py2

(py2) C:\Users\Makarevich>python --version
Python 2.7.13 :: Continuum Analytics, Inc.

(py2) C:\Users\Makarevich>cd C:\OutWiker

(py2) C:\OutWiker>pip install --user -r requirements.txt
Collecting Pillow==4.0.0 (from -r requirements.txt (line 1))
  Using cached Pillow-4.0.0-cp27-cp27m-win_amd64.whl
Collecting pyenchant==1.6.8 (from -r requirements.txt (line 2))
  Using cached pyenchant-1.6.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\makare~1\appdata\local\temp\pip-build-_lkpnp\pyenchant\setu
p.py", line 210, in <module>
        import enchant
      File "enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via yo
ur OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\makare~1
\appdata\local\temp\pip-build-_lkpnp\pyenchant\

**Comment by Jenyay** [comment]
Скачайте для Pyenchant по этой ссылке инсталлятор под Windows - https://pypi.python.org/pypi/pyenchant/

**Comment by MakarevichDmitry** [comment]
Видимо, проблема в моём Win64:


(C:\ProgramData\Miniconda3) C:\Users\Makarevich>activate py2

(py2) C:\Users\Makarevich>python --version
Python 2.7.13 :: Continuum Analytics, Inc.

(py2) C:\Users\Makarevich>conda install pyenchant
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - pyenchant


(py2) C:\Users\Makarevich>pip install pyenchant
Collecting pyenchant
  Using cached pyenchant-1.6.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\makare~1\appdata\local\temp\pip-build-hkkixb\pyenchant\setu
p.py", line 210, in <module>
        import enchant
      File "enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via yo
ur OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\makare~1
\appdata\local\temp\pip-build-hkkixb\pyenchant\

(py2) C:\Users\Makarevich>pip update pip
ERROR: unknown command "update"

(py2) C:\Users\Makarevich>pip upgrade pip
ERROR: unknown command "upgrade"

(py2) C:\Users\Makarevich>cd C:\OutWiker

(py2) C:\OutWiker>pip install pyenchant-1.6.8.tar.gz
Processing c:\outwiker\pyenchant-1.6.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\makare~1\appdata\local\temp\pip-blfdub-build\setup.py", lin
e 210, in <module>
        import enchant
      File "enchant\__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant\_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via yo
ur OS package manager, or use a pre-built binary wheel from PyPI.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\makare~1
\appdata\local\temp\pip-blfdub-build\

(py2) C:\OutWiker>conda install pyenchant-1.6.8.tar.gz
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - pyenchant-1.6.8.tar.gz


(py2) C:\OutWiker>

**Comment by Jenyay** [comment]
Да, похоже, что с установкой 64-битной pyenchant есть проблемы.

**Comment by MakarevichDmitry** [comment]
Под Ubuntu 16 возникли следующие ошибки. Привожу Лог.

pip install --user -r requirements_dev.txt
Collecting fabric (from -r requirements_dev.txt (line 1))
  Downloading Fabric-1.13.2-py2-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 419kB/s 
Collecting cx_Freeze==4.3.3 (from -r requirements_dev.txt (line 2))
  Downloading cx_Freeze-4.3.3.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 499kB/s 
Collecting paramiko<3.0,>=1.10 (from fabric->-r requirements_dev.txt (line 1))
  Downloading paramiko-2.2.1-py2.py3-none-any.whl (176kB)
    100% |████████████████████████████████| 184kB 466kB/s 
Collecting pynacl>=1.0.1 (from paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading PyNaCl-1.1.2-cp27-cp27mu-manylinux1_x86_64.whl (539kB)
    100% |████████████████████████████████| 542kB 398kB/s 
Collecting bcrypt>=3.1.3 (from paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading bcrypt-3.1.3-cp27-cp27mu-manylinux1_x86_64.whl (57kB)
    100% |████████████████████████████████| 61kB 536kB/s 
Collecting cryptography>=1.1 (from paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading cryptography-1.9.tar.gz (409kB)
    100% |████████████████████████████████| 419kB 460kB/s 
Collecting pyasn1>=0.1.7 (from paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 429kB/s 
Collecting six (from pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading cffi-1.10.0-cp27-cp27mu-manylinux1_x86_64.whl (392kB)
    100% |████████████████████████████████| 399kB 487kB/s 
Collecting idna>=2.1 (from cryptography>=1.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 669kB/s 
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 502kB/s 
Collecting enum34 (from cryptography>=1.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting ipaddress (from cryptography>=1.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko<3.0,>=1.10->fabric->-r requirements_dev.txt (line 1))
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 576kB/s 
Building wheels for collected packages: cx-Freeze, cryptography, pycparser
  Running setup.py bdist_wheel for cx-Freeze ... done
  Stored in directory: /home/makarevich/.cache/pip/wheels/a1/3e/5f/1d29dbff2428884d59d843b43056994245779325f7d82fbb03
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /home/makarevich/miniconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z0xdxS/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpT6CeMkpip-wheel- --python-tag cp27:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:15:17: fatal error: ffi.h: Нет такого файла или каталога
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Z0xdxS/cryptography/setup.py", line 321, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 315, in __init__
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 361, in fetch_build_eggs
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 428, in fetch_build_egg
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 664, in easy_install
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 694, in install_item
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 875, in install_eggs
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1102, in run_setup
  distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
  Complete output from command /home/makarevich/miniconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z0xdxS/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:15:17: fatal error: ffi.h: Нет такого файла или каталога
  compilation terminated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Z0xdxS/cryptography/setup.py", line 321, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 315, in __init__
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 361, in fetch_build_eggs
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 428, in fetch_build_egg
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 664, in easy_install
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 694, in install_item
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 875, in install_eggs
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
    File "/home/makarevich/miniconda3/envs/py2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1102, in run_setup
  distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed cleaning build dir for cryptography
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: /home/makarevich/.cache/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
Successfully built cx-Freeze pycparser
Failed to build cryptography
Installing collected packages: six, pycparser, cffi, pynacl, bcrypt, idna, asn1crypto, enum34, ipaddress, cryptography, pyasn1, paramiko, fabric, cx-Freeze
  Running setup.py install for cryptography ... error
    Complete output from command /home/makarevich/miniconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z0xdxS/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pM1ZFR-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-2.7/cryptography
    creating build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-2.7/cryptography/x509
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
    running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/makarevich/miniconda3/envs/py2/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: Нет такого файла или каталога
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/makarevich/miniconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Z0xdxS/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pM1ZFR-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-Z0xdxS/cryptography/

**Comment by Jenyay** [comment]
Похоже, не хватает библиотек SSL. Перед установкой попробуйте сделать 

`sudo apt-get install libssl-dev`

**Comment by MakarevichDmitry** [comment]
Очередная попытка на Ubuntu привела меня к следующим ошибкам:

sudo apt-get install python-wxgtk-webview3.0
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
E: Не удалось найти пакет python-wxgtk-webview3.0
E: Не удалось найти пакет с помощью glob «python-wxgtk-webview3.0»
E: Не удалось найти пакет с помощью regex «python-wxgtk-webview3.0»


fab run
bash: /home/makarevich/.local/bin/fab: /home/makarevich/miniconda3/envs/py2/bin/python: плохой интерпретатор: Нет такого файла или каталога

**Comment by Jenyay** [comment]
Нужно устанавливать libwxgtk-webview3.0-0v5

**Comment by Jenyay** [comment]
Если Ubuntu 16.04, то python-wxgtk-webview3.0 устанавливать не надо - эта библиотека была выделена отдельно из libwxgtk-webview3.0 в 16.10.

**Comment by MakarevichDmitry** [comment]
ясно. Получается, всё что нужно установлено, но всёравно не запускается.
fab run
bash: /home/makarevich/.local/bin/fab: /home/makarevich/miniconda3/envs/py2/bin/python: плохой интерпретатор: Нет такого файла или каталога

**Comment by MakarevichDmitry** [comment]
В итоге отказался от этой затеи и сделал так:
sudo apt-add-repository ppa:outwiker-team/ppa
sudo apt-get update
sudo apt-get install outwiker
outwiker
