### ISSUE TITLE
Не работает навигация по словам по Ctrl+Left/Right на викистранице

### ISSUE THREAD

**Issue by zimin-krsk** [Jenyay/outwiker#356]
На странице с вики-разметкой при попытке навигации по словам по горячим клавишам Ctrl+Left фокус уходит на панель с деревом заметок, по Ctrl+Right ничего не происходит.
На текстовой странице навигация работает между тем.

Операционная система - Ubuntu 16.04.2 LTS (Xenial Xerus)
Версия OutWiker - 2.0.0.822

**Comment by krsk-dev** [comment]
По горячим клавишам Ctrl+Shift+Left/Right - навигация на викистранице при этом работает

**Comment by Jenyay** [comment]
Подтверждаю.

**Comment by sevka** [comment]
Мне тоже сильно мешает этот баг. Бывает пишу что-то, хочу вернуться наазад на слово и тут о-па, курсор улетает на дерево заметок. Проверил, хоткеи прописаны на gotoprevword и gotonextword и больше комбинации Ctrl+Left и Ctrl+Right ни на что не назначены.
