### ISSUE TITLE
(:style:)

### ISSUE THREAD

**Issue by MakarevichDmitry** [Jenyay/outwiker#357]
Если очень хочется пользовательское выделение текста, то можно воспользоваться плагином **Style**, подтянуть знания в `CSS` и написать примерно следующее на вкладке **Вики**:
```
(:style:)
foo{background-color: black; color:white;}
(:styleend:)
<foo> bar </foo>
```
Тогда OutWiker мне подсветит ту часть заметки тем стилем, который Я назначил.
**Но можно-ли проще?**

**Comment by Jenyay** [comment]
В следующей версии я добавлю новые команды в викинотацию для раскраски текста.
