### ISSUE TITLE
матрицу не получается отобразить почему-то

### ISSUE THREAD

**Issue by vadrer** [Jenyay/outwiker#365]
текст, {$$
\begin{pmatrix}
   a & b \\
   c & d
\end{pmatrix}
$$}
никак не отображается, никак
например {$x_1$} отобраажется нормально, а также разные другие формулы, как {$ ...  $}, так и {$$ ... $$}

пример матрицы взял из https://khan.github.io/KaTeX/function-support.html 

у кого-нибудь получилось "увидеть" матрицы??

2.0.0.822 и плагин, который шёл вместе со "всё включено"

заранее спасибо :)

**Comment by vadrer** [comment]
... получилось, надо просто писать в одну строку...
"обидное" ограничение, к тому же - если скопировать теХ-вывод формули из Maxima'ы - как правило не получится отобразить, формулу надо будет "дорабатывать"

**Comment by Jenyay** [comment]
Я пометил это сообщение как баг, надо будет проверить, что там не так с переносом строк.

**Comment by Jenyay** [comment]
Попробуйте исправленную версию плагина (см. вложение).
[texequation-2.0.3.zip](https://github.com/Jenyay/outwiker/files/1471973/texequation-2.0.3.zip)

**Comment by vadrer** [comment]
попробовал,
помогло,
спасибо :)
