### ISSUE TITLE
Не полностью выделяется код в формате Markdown

### ISSUE THREAD

**Issue by shureek** [Jenyay/outwiker#366]
Когда в формате markdown ввожу код, он выделяется не полностью.

Ввел код (видно, что выделение справа обрезано):  
![Код](https://user-images.githubusercontent.com/2562878/32271897-0712659e-bf0d-11e7-862f-a8314e35035a.png)

Прокрутил вправо, выделение вообще уехало:  
![Прокрутил экран](https://user-images.githubusercontent.com/2562878/32271898-08d912e2-bf0d-11e7-88d0-1c60cb86f7d9.png)

Версия 2.1.0.830 под Windows 10 x64

**Comment by BaNru** [comment]
Это выделение в режиме просмотра, markdown тут не при чём.
Надо поправить стили темы.

**Вики** и **HTML** разметра код выделяет через **<CODE>** (и это правильно), markdown выделяет через **<PRE>**.
При этом во всех стиля или почти во всех, что я посмотрел есть стили для PRE, но нет для CODE (и это не правильно). То есть для Вики и HTML разметки вообще нет описания стилий для вставки кода. Тут надо придти к общему варианту.

В данном случае для markdown исправление очень простое - добавить в опимание стилей для pre новое свойство overflow: auto;

На данном этапе можно закрыть этот вопрос добавив **pre, code {}**
Получится типа такого
```
pre, code {
....
	overflow: auto;
}
```

**Comment by Jenyay** [comment]
Я думаю, что лучше добавить перенос строк. В этом случае с точки зрения некоторых языков это будет выглядеть не очень корректно (не надо было такие длинные строки писать), но нагляднее.

![2017-12-09 19-21-00](https://user-images.githubusercontent.com/166281/33797286-486f69d4-dd16-11e7-8529-934756d4e24c.png)

**Comment by BaNru** [comment]
Во всех IDE есть кнопочка "включить перенос строк".
Вот это будет правильно.

Это можно реализовать через программу и в случае выбранной опции динамически добавлять во время генерации страницы **white-space:pre-wrap** внутрь pre, code{} или добавлять отдельное правило вконце стилей. Ну это уже думаю и без меня понятно.

И ещё лучше эту функцию сделать глобальной настройкой, с возможностью менять локально для каждой страницы.

Либо можно написать маленький JS-скрипт с кнопочкой над PRE/CODE (могу написать) и внедрить его во все темы. Но я однозначно за вариант выше.

Однако, **overflow: auto;** в "**pre, code**" - стоит сделать в любом случае.

А пока это не реализовано, кому срочно надо - предлагаю ручками внести изменения у себя в любимую тему глобально или локально в необходимую страницу. (Кстати, где глобально стили лежат на линуске? Вшиты в питон? Я что-то не нашел). Либо модулями [HtmlHeads](http://jenyay.net/Outwiker/HtmlHeads) или [Style](http://jenyay.net/Outwiker/StylePlugin)
```
pre, code {
	overflow: auto;
	white-space:pre-wrap; /* строка по желанию */
}
```
===

Ещё обнаружил маленькую ошибку. Внутрь сгенерированого PRE добавляется лишний SPAN
http://dl4.joxi.net/drive/2017/12/09/0004/2123/305227/27/34a21c5b75.png
В вики такого не обнаружено.

**Comment by Jenyay** [comment]
Пока я сделал с переносом строк, надо подобное сделать для викинотации (добавить стиль в плагин Source). По поводу настройки - очень уж специфическая получается настройка, к тому же трудно описываемая, чтобы было понятно пользователю.

Стили лежат в папке программы в папке styles.

Не знаю, настолько этот span лишний, может быть авторы парсера Markdown его добавили с какой-то целью.

**Comment by Jenyay** [comment]
А с плагином Source перенос строк не пройдет, там тогда могут некорректно отображаться номера строк.

![_461](https://user-images.githubusercontent.com/166281/33798274-91298e7e-dd26-11e7-9dc8-1bcc1fb8510f.png)

**Comment by BaNru** [comment]
Чего там специфического? Не специфичнее, чем "размер табуляции" :)

Еле обновил этот Сорс. В папке лежала старая версия. Удалил её, залил новую последнюю с сайта. Слетел проект. Заново открыл. И на странице Вики вообще пустотат, во всём дереве. Просмотр и HTML нормально. Удалил и заново распаковал. Опять проект слетел. Заново открыл, но вроде заработало. При этом тестовая страница обнулилась. Хорошо что не рабочая.

Ну это ладно, спишем на частный случай. Суть в том, что нет там циферок в этом плагине! Проверил несколько языков на нескольких темах. При этом не оказалось поддержки PHP. Какой-то не очень хороший плагин.
http://dl4.joxi.net/drive/2017/12/09/0004/2123/305227/27/7310fa925f.png
Если скажешь тему и язык, то посмотрю и может подскажу чего интересного.

Рекомендую рассмотреть вариант перехода на js подсветку: highlightjs или ace.js или CodeMirror (последние два для редактирования кода тоже хороши). Как говорит Артемий Лебедев - долго, дорого, о**енно.

В них куча тем и языков. Последние два (один из них) круто было бы внедрить в редакторы, чтобы стразу по ходу набора подсвечивали, как IDE, но это конечно только мечты.

===
Еле нашёл стили. На убунту /usr/share/outwiker/, а я искал в домашней дерриктории, в конфигах. Не очень удобно получается, без прав админа не изменить. Рядом с плагинами им место. Ну да ладно, это уже другая тема.

**Comment by Jenyay** [comment]
Надо посмотреть, если JS-библиотеки будут лучше, то можно перейти.
