### ISSUE TITLE
Ошибка 22: Invalid mode or filename

### ISSUE THREAD

**Issue by shureek** [Jenyay/outwiker#367]
Как-то при переключении с одной вкладки на другую возникла такая ошибка:
```
Невозможно сохранить параметры страницы
[Errno 22] invalid mode ('wb') or filename:
u'......\__page.opt'
```
Делал перенос некоторых участков текста из одной страницы в другую. При этой ошибке буфер не сохранился, текст на старой вкладке уже был удален, а в новую (на которой ошибка) уже вставить нечего.

![Invalid mode or filename](https://user-images.githubusercontent.com/2562878/32272281-832995de-bf0e-11e7-8077-f3df5f6425cf.png)

Версия 2.1.0.830 под Windows 10 x64

**Comment by Jenyay** [comment]
Такое может быть, если файл __page.opt из заметки в этот момент был занят другим процессом.

**Comment by shureek** [comment]
Если где-то есть лог, могу найти, приложить

**Comment by shureek** [comment]
Ясно, странно. Если больше не вылезет, то закрою

**Comment by Jenyay** [comment]
Лог должен быть в C:\Users\USERNAME\AppData\Roaming\outwiker\outwiker.log

**Comment by Jenyay** [comment]
Может быть программа Dropbox-а блокирует файлы на время синхронизации?

**Comment by shureek** [comment]
Вот лог:
```
2017-11-01 11:55:01 - START
Traceback (most recent call last):
  File "src\outwiker\pages\wiki\basewikipageview.py", line 200, in onTabChanged
  File "src\outwiker\pages\html\basehtmlpanel.py", line 230, in savePageTab
  File "src\outwiker\core\config.py", line 182, in value
  File "src\outwiker\core\config.py", line 56, in set
  File "src\outwiker\core\config.py", line 67, in save
IOError: [Errno 22] invalid mode ('wb') or filename: u'D:\\Dropbox\\Outwiker\\\u0420\u0430\u0431\u043e\u0442\u0430\\\u041f\u0430\u0442\u0440\u0438\u043e\u0442\\__page.opt'
```

**Comment by shureek** [comment]
Возможно, DropBox. Проверю это.

**Comment by shureek** [comment]
Больше не появлялось. Но на всякий случай перенес в другую папку.

Думаю, можно закрыть.
