### ISSUE TITLE
Ctrl + cursor = прыгать по словам

### ISSUE THREAD

**Issue by vadrer** [Jenyay/outwiker#379]
каждый раз - прыгать по словам - испытываю неудобства.
почему не работает Ctrl + cursor?
:)

**Comment by Jenyay** [comment]
Это известная проблема, надеюсь ее скоро исправить.

**Comment by vadrer** [comment]
заранее благодарен.
тогда уж - чтобы два раза не вставать - Ctr+Up/down - предлагаю - scroll (но не настаиваю конечно же)

**Comment by vadrer** [comment]
хмммм.... а сейчас прыгает.....

**Comment by Jenyay** [comment]
Об этой ошибке уже есть сообщение - https://github.com/Jenyay/outwiker/issues/356
