### ISSUE TITLE
Заголовок страницы по умолчанию

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#399]
При создании новой страницы в поле ввода заголовка страницы вставлять текст по шаблону, например, текущую дату.

Шаблон должен меняться в настройках.

**Comment by KeyJoo** [comment]
Очень удобная фича для шаблона. Мне нравится такая реализация в 2 программах на Linux: TomBoy, RedBook.

**Comment by Jenyay** [comment]
Complete
