### ISSUE TITLE
Возможность сделать иконки для главных веток

### ISSUE THREAD

**Issue by reifwp** [Jenyay/outwiker#400]
Уважаемый разработчик , посмотрите древнею прогу Mars Notebook https://goo.gl/C3YSqp . Там есть классные идеи ..Возьмите на вооружение .. Например мне очень нравится, возможность сделать для веток дерева иконки .Когда веток много, просто глазами пробежался и все .Да и как-то роднее свое дерево становится ..Я понимаю,кому это может быть категорически не понравится .Ну так надо сделать возможность,установки по желанию иконки . Спасибо

**Comment by Jenyay** [comment]
И сейчас в OutWiker можно устанавливать иконки для заметок.

**Comment by reifwp** [comment]
Ага посмотрел,можно на заметку .. Классно . А на ветки главные что ли нельзя ?

**Comment by Jenyay** [comment]
А что значит на "главные ветки"?

**Comment by reifwp** [comment]
Ну я вчера только скачал вашу прогу потыкал интерфейс ..Очень нравится, что вики и html  .. Посмотрел на ветку слева, вспомнил старый mars notebook . Думал,картинки было бы классно,написал вам, а вы говорите есть ..Проверил, да есть ..А я ветки не создавал, там что были по умолчанию для теста ..Так вот на материнскую ветку ветку под номером 11 , значок не ставится ..А ну это я перепутал наверное, это самая главная ветка .На нее только не ставится ..А нас остальные ставится, извиняюсь .

**Comment by Jenyay** [comment]
Тогда закрываю тему. Если очень нужна иконка на корне дерева, то создайте новую issue.
