### ISSUE TITLE
какой PIL брать?

### ISSUE THREAD

**Issue by vadrer** [Jenyay/outwiker#405]
пытююсь запустить из src, python3.6

`  File "C:\vad\wx-p3.git\src\outwiker\core\iconmaker.py", line 3, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
OnInit returned false, exiting...`

http://www.pythonware.com/products/pil/ написано "A version for 3.X will be released later."

**Comment by Jenyay** [comment]
Нужен pillow. Версия практически не важна, в последнее время собираю с использованием pillow 5.0.0 - https://pypi.python.org/pypi/Pillow/5.0.0

**Comment by vadrer** [comment]
прекрасно.
спасибо, заработало :)
