### ISSUE TITLE
Запуск приложения после закрытия на не основном дисплее в windows

### ISSUE THREAD

**Issue by ppv77** [Jenyay/outwiker#406]
Если приложение закрыть на **не** основном дисплее, повторный запуск приводит к изменению размеров окна и съезжанию всх панелей

![2018-02-27 16_00_39-](https://user-images.githubusercontent.com/17343183/36730151-71aa8e64-1bd7-11e8-908a-51121c32c831.png)

**Comment by twobolts** [comment]
для windows 10 проблема так же актуальна.

**Comment by Jenyay** [comment]
Это какая версия OutWiker?

**Comment by Jenyay** [comment]
Ок. Попытаюсь повторить, хотя сходу такой глюк получить не удалось.

**Comment by twobolts** [comment]
Проблема наблюдается, если главный монитор настроен справа. В этом случае координаты приложения на втором мониторе получаются отрицательными. Однако в конфиг при закрытии сохраняется нулевое значение координат приложения и отрицательная длинна. Закину пулреквест, на починку.

**Comment by Jenyay** [comment]
Попробуйте новую нестабильную версию, туда включено исправление от @twobolts.

**Comment by Jenyay** [comment]
Fixed
