### ISSUE TITLE
OutWiker v2.1.0.836 (portable) & problem on start in WindowsXP

### ISSUE THREAD

**Issue by Cipollino** [Jenyay/outwiker#407]
Dear programmers of OutWiker, I have the WindowsXP - SP3 and OutWiker v2.1.0.834 in portable version and it's an very good program.

I have upgraded my OutWiker configuration with your last version unstable v2.1.0.836 (portable) and the program not start.
The error is displayed in an popup like this:

Impossibile trovare il punto di ingresso GetFinalPathNameByHandleW della procedura nella libreria di collegamento dinamico KERNEL32.DLL

From this last version your software is not compatible with WindowsXP or you have any solution for this problem?

Many Thanks for your interest to my problem.

Bye for now.

**Comment by Jenyay** [comment]
OutWiker 2.1.0.836 migrated from Python 2.7 to Python 3.5 / 3.6. Unfortunately Windows XP was supported Python 3.4, but not Python 3.5. I'm not sure that OutWiker will work with Python 3.4. I'll try, but I can not guarantee correct work.

**Comment by Cipollino** [comment]
OK dear Programmer, when you have the work, give to me the link for software test.

Many thanks for your attention to my problem.

Bye for now.
