### ISSUE TITLE
Возможность изменять цвет фона основных панелей окна

### ISSUE THREAD

**Issue by Jenyay** [Jenyay/outwiker#448]
Возможность изменять цвет фона дерева заметок, облака тегов и списка прикрепленных файлов.

**Comment by SN-CH** [comment]
Это было бы очень хорошо. Но может быть не только фона этих панелей, но и самого дерева (светлое дерево на тёмном фоне...)?

**Comment by Jenyay** [comment]
> Но может быть не только фона этих панелей, но и самого дерева...

Под "цвет фона дерева заметок" именно это я и имел в виду.

**Comment by Jenyay** [comment]
Complete
