### ISSUE TITLE
Option sql missing from sourcecode

### ISSUE THREAD

**Issue by awrog** [Jenyay/outwiker#473]
When I format some source-code the option **sql** is no longer available  
![screenshot - 11_14_2018 14_02_43](https://user-images.githubusercontent.com/12153667/48484309-15f36f80-e816-11e8-8ec9-004d0de260fb.png)

When I add it manually it works just fine:  
![screenshot - 11_14_2018 14_04_32](https://user-images.githubusercontent.com/12153667/48484484-88fce600-e816-11e8-9f3b-41be5a3517a8.png)

![screenshot - 11_14_2018 14_05_05](https://user-images.githubusercontent.com/12153667/48484398-4f2bdf80-e816-11e8-8ebe-8258d56f5331.png)

**Comment by Jenyay** [comment]
You need to add SQL in the settings. 
![source_sql](https://user-images.githubusercontent.com/166281/48501137-8964a380-e84d-11e8-829a-30fab8806088.png)

**Comment by awrog** [comment]
Thanks, I feel silly now.
