### ISSUE TITLE
3.0.858: сломан переход по ссылкам из результата глобального поиска

### ISSUE THREAD

**Issue by adeptg** [Jenyay/outwiker#478]
Тестировал на KDE и XFCE, т.е., не похоже на что-то, зависящее от DE. Раньше работало. outwiker установлен из snap.
Как воспроизвести:

1. Tools -> Global search
2. Найти что-нибудь
3. Кликнуть на любую ссылку. Вместо ожидаемого перехода на страницу откроется просто белая страница

**Comment by Jenyay** [comment]
Да, я знаю. Уже исправил. В ближайшие дни будет новая версия с этим исправлением.

**Comment by adeptg** [comment]
Спасибо!
