### ISSUE TITLE
Outwiker для Linux не видит некоторые установленные в системе шрифты

### ISSUE THREAD

**Issue by SN-CH** [Jenyay/outwiker#488]
Интересная ошибка. Сразу оговорюсь, что речь идёт не об экзотике. Outwiker, установленный на Lubuntu 20.04 x64, не видит шрифты «Noto Sans Mono» и «Noto Mono». Я имею в виду, что названия именно этих двух шрифтов отсутствуют в диалоге выбора шрифта в настройках (раздел «Editor», кнопка «Font»). Все остальные моноширинные шрифты присутствуют в списке. Во всех остальных программах указанные шрифты выбираются без малейших проблем.

**Comment by Jenyay** [comment]
Создайте папку ~/snap/outwiker/current/.fonts/ и туда можно скопировать нужные шрифты, после чего нужно запустить команду fc-cache -fv

**Comment by SN-CH** [comment]
Ваш совет помог. Большое спасибо!

Однако, меня несколько удивило то, что всё равно остались некоторые различия в том, как шрифт выглядит в Outwiker по сравнению со стандартными программами. На рисунке 
![Screen-shot_2020-05-28_11-02](https://user-images.githubusercontent.com/42577865/83124486-f3b30100-a0de-11ea-9daa-c5fe8994b5ab.png) приведены рядом окна Kate и Outwiker. Шрифт один и тот же — Noto Mono 13 pt. В окне Outwiker символы как будто чуть больше или совсем немного растянуты по вертикали и выглядят немного иначе (не в смысле очертаний, конечно, а rendering). Разница небольшая, поэтому само по себе это отнюдь не проблема, но, я подумал, что самый факт может быть Вам небезынтересен.

**Comment by Jenyay** [comment]
Да, различия есть, такое ощущение, что слева он чуть помельче. С чем это может быть связано трудно сказать.

**Comment by Jenyay** [comment]
Но раз проблема со шрифтами решена, issue закрываю.
