### ISSUE TITLE
Возможность добавления некоторых параметров для управления внешним видом списка меток (tags)

### ISSUE THREAD

**Issue by SN-CH** [Jenyay/outwiker#497]
На сегодняшний день есть возможность менять цвет шрифта самих меток, а также цвет их фона (причём можно задать разные цвета для разных состояний меток).

Нельзя ли сделать ещё один шаг и реализовать следующие возможности:
1) выбор шрифта меток (и, разумеется, размера оного);
2) отключение (в виде переключателя) функции вывода часто используемых меток увеличенным шрифтом (в некоторых ситуациях это удобно, но, как мне кажется, не всегда);
3) указание (опять же в виде переключателя) выводить список меток в виде, э-э-э... именно списка, а не абзаца. Я имею в виду, чтобы при установке последнего переключателя метки выводились бы как

> ААА
> БББ
> ВВВ

а не

> ААА БББ ВВВ

как это сделано сейчас.

Весьма вероятно, что это не самые востребованные функции, но может можно реализовать их в виде флагов в Outwiker.ini, чтобы не загромождать интерфейс и не делать лишнюю работу?

**Comment by Jenyay** [comment]
Complete in 3.3.0.928 beta
