### ISSUE TITLE
Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

### ISSUE THREAD

**Issue by RailiQwan** [Jenyay/outwiker#501]
Добрый день. С некоторых пор - к сожалению я не уловил когда это появилось - я давно не пользовался вашей программой и вообще компьютером - при попытке скачать веб страничку из сети или с диска появляется вот это:  

[001] Начало скачивания
[002] Неправильная ссылка или формат файла
[003] Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

Сейчас я использую Windows 10. 

Версия программы 3.0.0 и 3.1.0.892 beta (27.07.2021)
После установки старой версии 2*** снова всё заработало.

**Comment by smaragdus** [comment]
I have the same problem using [OutWiker](https://github.com/Jenyay/outwiker) version [3.0.0.888](https://github.com/Jenyay/outwiker/releases/tag/stable_3.0.0.888), I always get an error message when I try to add a web page URL or a local HTML file:

**error:**

```
[001] Start downloading
[002] Invalid URL or file format
[003] Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?
```
**screen:**

![OutWiker 3 0 0 888 - 2022-02-05 - parser error - 001](https://user-images.githubusercontent.com/9025757/152616852-6c9e4d1b-b750-45c8-ae5c-41d6011afd3d.png)

For me [WebPage](https://jenyay.net/Outwiker/WebPageEn) plug-in does not work.

**Comment by smaragdus** [comment]
@Jenyay 

I finally tested version [3.1.0](https://github.com/Jenyay/outwiker/releases/tag/stable_3.1.0.900) and the download problem is really fixed, thanks!

Off-topic- [OutWiker](https://jenyay.net/Outwiker/English) uses **Internet Explorer** as rendering engine, do you plan to switch to something else?

Regards
