### ISSUE TITLE
Под Manjaro Linux даже не запускается

### ISSUE THREAD

**Issue by native-engine** [Jenyay/outwiker#516]
Давно мечтал кропать дизайн-документы в формате CHM и тут увидел эту программу, установил, а она даже не запускается :)

**Comment by Jenyay** [comment]
А какая ошибка? По идее работать должно, я сам сижу в Manjaro и пробую в нем все сборки.

**Comment by native-engine** [comment]
А как запустить в терминале? А то я пробую кликать иконку :)

**Comment by Jenyay** [comment]
А через что установили snap или flatpak?

**Comment by native-engine** [comment]
Pamac

**Comment by Jenyay** [comment]
Кажется, что тот, кто делал пакет для Arch, его уже давно не поддерживает.

**Comment by native-engine** [comment]
Вполне возможно... а жаль! Пакетами snap или flatpak я давно не пользуюсь, как ушёл с Ubuntu.
