### ISSUE TITLE
Unable to compile due to problems with python-cyhunspell (way to compile without it?)

### ISSUE THREAD

**Issue by Bluey26** [Jenyay/outwiker#571]
Hi, i wanted to test this software.

I am using archlinux and that means i need to compile the program from the source code to use it. (I tried flatpak but i was unable to use it under wayland).

I was wondering if there was a way to compile without `cyhunspell` (and `cpython`) so i can test this program.

I also have tried to compile it from the source code as its said in https://www.jenyay.net/Outwiker/English#source without luck, due to problems with the same library (i guess).

Some of the error i got were:

`ModuleNotFoundError: No module named 'buildtools'` (even when i installed buildtools after `pipenv shell`)

`pipenv update -d` does not work for me, for some reason (possible external problem)

`PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’` When i tried to compile https://aur.archlinux.org/packages/python-cyhunspell

As far as i understand, hunspell is a dictionary and grammar check tool, and that means compilation without it would work.

Info:
OS: `Arch linux`
Python: `Python 3.12.7`

Thanks in advance.

**Comment by Jenyay** [comment]
OutWiker sources contains the patched cyhunspell in the depends/cyhunspell directory. Try it.

**Comment by Bluey26** [comment]
> OutWiker sources contains the patched cyhunspell in the depends/cyhunspell directory. Try it.

Excellent, that solved it for me. I was unaware of your patched versions, sorry.

What i did was:
cloning the repository https://github.com/Jenyay/cython_hunspell

I also needed to clone https://github.com/Jenyay/py_cache_manager to make the program work.

After this, i got the outwiker window working. Just as a detail, the program seems to work in wayland.

Before closing this as solved, i have this question:

Should i use the custom wx-python version provided in https://github.com/Jenyay/wxpython ? what is the difference with the normal ones for outwiker?

Thank you very much.

**Comment by Bluey26** [comment]
> In Linux, no. This version fix one problem with emoji in Windows.

I see, thanks again, i will mark this as solved.
