### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by vasilykraev** [Jenyay/outwiker#6]
I think, what snippets is really necessary feature. Not only for code, but as a replacement for wiki-templates. At this moment I have some template-files, and copy-paste code from them to new note. Would like to use shortcuts :)

**Comment by Jenyay** [comment]
Completed with the [Snippets](http://jenyay.net/Outwiker/SnippetsEn) plugin.

**Comment by deterok** [comment]
Wow! Three years have passed!
