### ISSUE TITLE
Синхронизация

### ISSUE THREAD

**Issue by sergeyklay** [Jenyay/outwiker#7]
Здравствуйте.

Пишу сюда, как напоминалку, на будущее.
Было бы не плохо реализовать синхронизацию в облако или, хотя бы описать публичный API для реализации подобного функционала через подключаемые модули (плагины).

**Comment by codenull** [comment]
Здравствуйте.

А чем плох вариант хранить все данные в каталоге сервиса типа дропбокс? По-моему, таже самая синхронизация, но без плагина.
