### ISSUE TITLE
Что открыть по умолчанию ?

### ISSUE THREAD

**Issue by sergeyklay** [Jenyay/outwiker#8]
Привет!

Реализуйте пожалуйста некий чекбокс в настройках — что открывать по умолчанию при запуске программы:
- [ ] Пустое окно программы
- [ ] Диалог открытия
- [ ] Предыдущий файл (только для чтения?)

**Comment by deterok** [comment]
@Jenyay я бы мог взяться за это если бы ты показал куда нужно залезть, очень не хочется сидеть и копать самому 😃

**Comment by Jenyay** [comment]
Хорошо, добавлю себе в ToDo.
